sml702_hw02.pdf: sml702_hw02.tex
	pdflatex $<

clean:
	rm -f sml702_hw02.aux
	rm -f sml702_hw02.log
	rm -f sml702_hw02.blg
	rm -f sml702_hw02.bbl

spotless: clean
	rm -f sml702_hw02.pdf

.PHONY: clean spotless
