sml702_midterm_cheatsheet.pdf: sml702_midterm_cheatsheet.tex
	pdflatex $<

clean:
	rm -f sml702_midterm_cheatsheet.aux
	rm -f sml702_midterm_cheatsheet.log
	rm -f sml702_midterm_cheatsheet.blg
	rm -f sml702_midterm_cheatsheet.bbl

spotless: clean
	rm -f sml702_midterm_cheatsheet.pdf

.PHONY: clean spotless
